//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlkdstDB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class chiphi
    {
        public decimal Id { get; set; }
        public string sgtcode { get; set; }
        public string mancc { get; set; }
        public string tenncc { get; set; }
        public string iddv { get; set; }
        public Nullable<bool> tienmat { get; set; }
        public Nullable<decimal> ngoaite { get; set; }
        public string loaitien { get; set; }
        public Nullable<decimal> tigia { get; set; }
        public Nullable<decimal> tienvnd { get; set; }
        public Nullable<int> sokhach { get; set; }
        public string noidung { get; set; }
        public string ghichu { get; set; }
        public string nguoinhap { get; set; }
        public Nullable<System.DateTime> ngaynhap { get; set; }
        public string computer { get; set; }
        public Nullable<bool> del { get; set; }
        public string tenfileinvoice { get; set; }
        public string log_file { get; set; }
        public Nullable<decimal> idtour { get; set; }
    }
}
