//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlkdstDB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmfile
    {
        public decimal file_id { get; set; }
        public string loaifile { get; set; }
        public string tenfile { get; set; }
        public Nullable<decimal> idtour { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string log_file { get; set; }
    }
}
