//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlkdstDB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class hangkhong
    {
        public decimal id { get; set; }
        public string sgtcode { get; set; }
        public string mancc { get; set; }
        public string tenncc { get; set; }
        public string iddv { get; set; }
        public string hanhtrinh { get; set; }
        public string codebooking { get; set; }
        public string loaibooking { get; set; }
        public int chococ1 { get; set; }
        public decimal tiencoc1 { get; set; }
        public int chococ2 { get; set; }
        public decimal tiencoc2 { get; set; }
        public int chococ3 { get; set; }
        public decimal tiencoc3 { get; set; }
        public int sochoxuatve { get; set; }
        public decimal tiencocphat { get; set; }
        public decimal tiencochoan { get; set; }
        public string ghichu { get; set; }
        public string logfilehk { get; set; }
        public string nguoinhap { get; set; }
        public Nullable<System.DateTime> ngaynhap { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public Nullable<decimal> idtour { get; set; }
    }
}
