//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlkdstDB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachsan
    {
        public decimal Idks { get; set; }
        public Nullable<decimal> idtour { get; set; }
        public Nullable<int> stt { get; set; }
        public Nullable<System.DateTime> checkin { get; set; }
        public Nullable<System.DateTime> checkout { get; set; }
        public Nullable<System.DateTime> deadline { get; set; }
        public string maks { get; set; }
        public string tenks { get; set; }
        public string loaigia { get; set; }
        public string tinhtp { get; set; }
        public Nullable<int> sophong { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string dieuhanh { get; set; }
    }
}
