//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlkdstDB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tourleoblog
    {
        public decimal idlog { get; set; }
        public string sgtcode { get; set; }
        public string makh { get; set; }
        public string chudetour { get; set; }
        public Nullable<System.DateTime> batdau { get; set; }
        public Nullable<System.DateTime> ketthuc { get; set; }
        public string tuyentq { get; set; }
        public string diemtq { get; set; }
        public string chuongtrinhtour { get; set; }
        public Nullable<int> sokhachdk { get; set; }
        public string thongbaoloi { get; set; }
    }
}
