//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlkdstDB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class visa
    {
        public decimal visa_id { get; set; }
        public Nullable<decimal> idtour { get; set; }
        public string hoten { get; set; }
        public Nullable<bool> sex { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string passportno { get; set; }
        public Nullable<System.DateTime> doi { get; set; }
        public Nullable<System.DateTime> doe { get; set; }
        public string Nationality { get; set; }
        public string note { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoisua { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
    }
}
